### ISSUE TITLE
Auth Local no return custom error

### ISSUE THREAD

**Issue by johinsDev** [EQuimper/nodejs-api-boilerplate#85]
Passport local not return custom message error, always return unauthorized

**Comment by EQuimper** [comment]
Yes it's kind of hacky to change this with passport. https://github.com/jaredhanson/passport/blob/935fbdbc2f63eb0a746a3e1373fb112c5efee6b6/lib/middleware/authenticate.js#L23-L40

**Comment by EQuimper** [comment]
If you change the callback you need to do all the job after. This is one of the reason I keep it with just unauthorized :s
