### ISSUE TITLE
Call methods in toJSON

### ISSUE THREAD

**Issue by johinsDev** [EQuimper/nodejs-api-boilerplate#86]
for example this line

would 

```js
toJSON() {
    return {
      _id: this._id,
      title: this.title,
      text: this.text,
      author: this.author,
      createdAt: this.createdAt,
      favoriteCount: this.favoriteCount(),
    };
  },
```
or call isMyFavorite

**Comment by EQuimper** [comment]
Hey thank you for trying this boilerplate :) What you mean with the question. You ask for the naming ?

**Comment by johinsDev** [comment]
is posible call method in toJSON() method for example this.favoriteCount(), this method call method count in moongose is promise

**Comment by EQuimper** [comment]
Yes I pretty sure this work, must not be an async function

**Comment by EQuimper** [comment]
But maybe I'm wrong :)
